services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    rootDir: whatsapp_bot   # ✅ Directorio donde está package.json

    # =========================================================
    # 🔧 COMANDO DE BUILD (antes del despliegue)
    # =========================================================
    buildCommand: |
      echo "🛠️ [BUILD] Iniciando proceso de construcción del bot PETBIO..."
      
      # Dar permisos al script de build
      chmod +x ./render-build.sh && echo "✅ Permisos de render-build.sh asignados."
      
      # Ejecutar script de instalación de dependencias del sistema
      echo "🔧 [1/3] Ejecutando render-build.sh..."
      ./render-build.sh && echo "✅ Dependencias del sistema instaladas."
      
      # Instalar dependencias Node.js
      echo "📦 [2/3] Instalando dependencias Node..."
      yarn install --frozen-lockfile && echo "✅ Dependencias Node instaladas."
      
      # Instalar Puppeteer Chrome
      echo "🌐 [3/3] Instalando Chromium para Puppeteer..."
      npx puppeteer install chrome && echo "✅ Chromium instalado correctamente."
      
      echo "🎯 [BUILD COMPLETADO] Todos los pasos ejecutados correctamente."

    # =========================================================
    # 🚀 COMANDO DE INICIO (ejecuta el bot)
    # =========================================================
    startCommand: |
      echo "🚀 [START] Iniciando PETBIO WhatsApp Bot..."
      chmod +x ./render-start.sh && echo "✅ Permisos de render-start.sh verificados."
      ./render-start.sh && echo "✅ Bot iniciado correctamente."

    # =========================================================
    # 🌍 VARIABLES DE ENTORNO
    # =========================================================
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"

      # Puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"  # ❌ no saltar descarga; Puppeteer instalará Chromium correcto
      # - key: PUPPETEER_EXECUTABLE_PATH
      #   value: (No es necesario, Puppeteer lo detecta automáticamente)

      # API Keys / Servicios externos
      - key: OPENAI_API_KEY
        value: sk-proj-XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - key: TWILIO_SID
        value: ACXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - key: TWILIO_AUTH
        value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - key: TWILIO_NUMBER
        value: whatsapp:+14155238886
      - key: ADMIN_NUMBER
        value: whatsapp:+573007019277
      - key: VERIFY_SERVICE_SID
        value: VAXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      # URLs de integración PHP
      - key: CATALOG_URL
        value: http://php_integrator/catalogos.php
      - key: SUSCRIPCION_URL
        value: http://php_integrator/whatsapp-suscripcion.php

      # MySQL Local / Docker interno
      - key: MYSQL_HOST
        value: 172.22.0.2
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: R00t_Segura_2025!
      - key: MYSQL_DATABASE
        value: db__produccion_petbio_segura_2025

      # MQTT LavinMQ Cloud
      - key: MQTT_HOST
        value: duck.lmq.cloudamqp.com
      - key: MQTT_PORT
        value: "8883"
      - key: MQTT_USER
        value: xdagoqsj
      - key: MQTT_PASS
        value: flwvAT0Npo8piPIZehUr_PnKPrs1JJ8L
      - key: MQTT_TOPIC
        value: petbio/test

      # Supabase
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      - key: SUPABASE_DB_URL
        value: postgresql://postgres:R00t_Segura_2025!@db.jbsxvonnrahhfffeacdy.supabase.co:5432/postgres
