# =========================================================
# 🧠 Render Configuration - PETBIO WhatsApp Bot
# =========================================================
services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    rootDir: whatsapp_bot   # Aquí debe estar package.json

    # =========================================================
    # 🛠️ COMANDO DE BUILD (antes del despliegue)
    # =========================================================
    buildCommand: |
      chmod +x ./render-build.sh
      ./render-build.sh
      yarn install
      npx puppeteer install chrome

    # =========================================================
    # 🚀 COMANDO DE INICIO (ejecuta el bot)
    # =========================================================
    startCommand: ./render-start.sh

    # =========================================================
    # 🌍 VARIABLES DE ENTORNO
    # =========================================================
    envVars:
      # ===============================
      # Node / App
      # ===============================
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"

      # ===============================
      # API Keys / Servicios externos
      # ===============================
      - key: OPENAI_API_KEY
        value: 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
      - key: TWILIO_SID
        value: ACe15576d5f4212f1aa78999a3f53820d1
      - key: TWILIO_AUTH
        value: f462e76653a85ac6172d441a7bd67332
      - key: TWILIO_NUMBER
        value: whatsapp:+14155238886
      - key: ADMIN_NUMBER
        value: whatsapp:+573007019277
      - key: VERIFY_SERVICE_SID
        value: VA4c43e35a016e2242bb25a929b9b59cba
      - key: CATALOG_URL
        value: http://php_integrator/catalogos.php
      - key: SUSCRIPCION_URL
        value: http://php_integrator/whatsapp-suscripcion.php

      # ===============================
      # Usuarios locales / permisos
      # ===============================
      - key: LOCAL_UID
        value: "1000"
      - key: LOCAL_GID
        value: "1000"

      # ===============================
      # MySQL
      # ===============================
      - key: MYSQL_HOST
        value: 172.22.0.02
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: R00t_Segura_2025!
      - key: MYSQL_DATABASE
        value: db__produccion_petbio_segura_2025

      # ===============================
      # MQTT Cloud (CloudMQTT)
      # ===============================
      - key: MQTT_CLOUD_BROKER
        value: mqtts://duck.lmq.cloudamqp.com:8883
      - key: MQTT_CLOUD_USER
        value: xdagoqsj
      - key: MQTT_CLOUD_PASS
        value: flwvAT0Npo8piPIZehUr_PnKPrs1JJ8L

      # ===============================
      # Supabase / PostgreSQL
      # ===============================
      - key: SUPABASE_DB_URL
        value: postgresql://postgres:R00t_Segura_2025!@db.jbsxvonnrahhfffeacdy.supabase.co:5432/postgres
      - key: SUPABASE_HOST
        value: db.jbsxvonnrahhfffeacdy.supabase.co
      - key: SUPABASE_PORT
        value: "5432"
      - key: SUPABASE_USER
        value: postgres
      - key: SUPABASE_PASS
        value: R00t_Segura_2025!
      - key: SUPABASE_DB
        value: postgres
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
