services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    rootDir: whatsapp_bot

    buildCommand: |
      echo "🛠️ [BUILD] Preparando entorno Puppeteer + WhatsApp Web.js..."
      npm install
      npx puppeteer browsers install chrome --platform=linux --arch=x64 --force
      echo "✅ Chrome instalado en caché de Render."

    startCommand: |
      echo "🚀 Iniciando PETBIO WhatsApp Bot..."
      node whatsapp_bot/index.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

      # Puppeteer - Render Path
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-140.0.7339.207/chrome-linux64/chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"

      # ===============================
      # API Keys / Servicios externos
      # ===============================
      - key: OPENAI_API_KEY
        value: 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
      - key: TWILIO_SID
        value: ACe15576d5f4212f1aa78999a3f53820d1
      - key: TWILIO_AUTH
        value: f462e76653a85ac6172d441a7bd67332
      - key: TWILIO_NUMBER
        value: whatsapp:+14155238886
      - key: ADMIN_NUMBER
        value: whatsapp:+573007019277
      - key: VERIFY_SERVICE_SID
        value: VA4c43e35a016e2242bb25a929b9b59cba
      - key: CATALOG_URL
        value: http://php_integrator/catalogos.php
      - key: SUSCRIPCION_URL
        value: http://php_integrator/whatsapp-suscripcion.php

      # ===============================
      # MySQL
      # ===============================
      - key: MYSQL_HOST
        value: 172.22.0.2
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: R00t_Segura_2025!
      - key: MYSQL_DATABASE
        value: db__produccion_petbio_segura_2025

      # ===============================
      # MQTT Cloud (LavinMQ)
      # ===============================
      - key: MQTT_HOST
        value: duck.lmq.cloudamqp.com
      - key: MQTT_PORT
        value: "8883"
      - key: MQTT_USER
        value: xdagoqsj
      - key: MQTT_PASS
        value: flwvAT0Npo8piPIZehUr_PnKPrs1JJ8L
      - key: MQTT_TOPIC
        value: petbio/test

      # ===============================
      # Supabase
      # ===============================
      - key: SUPABASE_DB_URL
        value: postgresql://postgres:R00t_Segura_2025!@db.jbsxvonnrahhfffeacdy.supabase.co:5432/postgres
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
